"""Compute class weights (pos_weight) for the malaria binary classification task.

pos_weight = n_neg / n_pos is used to initialise BCEWithLogitsLoss so that the
model pays equal total attention to positives and negatives despite class imbalance.

Results are saved to configs/class_weights.yaml for use by the model config.

Usage::

    uv run python scripts/compute_class_weights.py

The script reads from the pre-built metadata cache (samples.parquet) so the DB is
not required.
"""

import os
import sys

import rootutils

rootutils.setup_root(__file__, indicator=".project-root", pythonpath=True)

from src.data.malaria_patch_datamodule import _split_by_patient_id

# ---------------------------------------------------------------------------
# Configuration — edit these or pass via env vars
# ---------------------------------------------------------------------------
CACHE_DIR = os.environ.get(
    "MALARIA_CACHE_DIR",
    "/data/mtanzer/malaria_cache",
)
SPLIT_SEED = int(os.environ.get("SPLIT_SEED", "42"))
TRAIN_RATIO = float(os.environ.get("TRAIN_RATIO", "0.7"))
OUTPUT_PATH = os.environ.get(
    "WEIGHTS_OUTPUT",
    os.path.join(os.path.dirname(__file__), "..", "data", "class_weights.yaml"),
)


def load_train_samples():
    """Load train samples from the pre-built metadata cache."""
    import pandas as pd

    samples_path = os.path.join(CACHE_DIR, "samples.parquet")

    if not os.path.isfile(samples_path):
        sys.exit(
            f"ERROR: samples.parquet not found at {samples_path}\n"
            "Run training once with prepare_data=True or run the full datamodule first."
        )

    samples_df = pd.read_parquet(samples_path)
    samples = samples_df.to_dict(orient="records")
    train_samples, _, _ = _split_by_patient_id(
        samples,
        [TRAIN_RATIO, (1 - TRAIN_RATIO) / 2, (1 - TRAIN_RATIO) / 2],
        SPLIT_SEED,
    )
    print(f"Train samples: {len(train_samples):,}")
    return train_samples


def compute_pos_weight(train_samples):
    """Count positives and negatives, return pos_weight = n_neg / n_pos.

    The parquet cache stores the binarised label as 'label' (0.0 or 1.0),
    regardless of which DB column was used (y_binary_strict / y_binary_inclusive).
    """
    n_pos = sum(1 for s in train_samples if s.get("label", 0) == 1)
    n_neg = sum(1 for s in train_samples if s.get("label", 0) == 0)
    n_total = len(train_samples)
    print(f"  Positives: {n_pos:,} ({100 * n_pos / n_total:.1f}%)")
    print(f"  Negatives: {n_neg:,} ({100 * n_neg / n_total:.1f}%)")
    if n_pos == 0:
        sys.exit("ERROR: no positive samples found — check 'label' column in samples.parquet")
    pos_weight = n_neg / n_pos
    print(f"  pos_weight = {n_neg} / {n_pos} = {pos_weight:.4f}")
    return pos_weight


def main():
    print("=" * 60)
    print("Malaria patch class weight computation")
    print("=" * 60)

    train_samples = load_train_samples()
    pos_weight = compute_pos_weight(train_samples)

    output = {
        "# Auto-generated by scripts/compute_class_weights.py. Do not edit manually.": None,
        "pos_weight": round(pos_weight, 4),
    }

    # Write YAML manually to get the comment at the top
    output_path = os.path.abspath(OUTPUT_PATH)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("# Auto-generated by scripts/compute_class_weights.py. Do not edit manually.\n")
        f.write(f"pos_weight: {pos_weight:.4f}\n")
    print(f"\nSaved to {output_path}")
    print(f"\nAdd to model config defaults:\n  defaults:\n    - class_weights\n")
    print(f"Wire into BCEWithLogitsLoss:\n  pos_weight:\n    _target_: torch.tensor\n    data: [${{pos_weight}}]\n")


if __name__ == "__main__":
    main()
